### ISSUE TITLE
Templates/MasterDataListコンポーネントをstorybook上で表示した際にエラーが発生する

### ISSUE THREAD

**Issue by fukudomeh** [fukudomeh/t-met_front#30]
# 概要
Templates/MasterDataListコンポーネントをstorybook上で表示した時、以下のエラーが発生する

```sh
Cannot read properties of undefined (reading 'divider')
TypeError: Cannot read properties of undefined (reading 'divider')
    at http://localhost:6006/main.iframe.bundle.js:8493:42
    at Ne (http://localhost:6006/vendors~main.iframe.bundle.js:238095:15534)
    at e.generateAndInjectStyles (http://localhost:6006/vendors~main.iframe.bundle.js:238095:11985)
    at http://localhost:6006/vendors~main.iframe.bundle.js:238095:19991
    at http://localhost:6006/vendors~main.iframe.bundle.js:238095:20119
    at O (http://localhost:6006/vendors~main.iframe.bundle.js:238095:20728)
    at renderWithHooks (http://localhost:6006/vendors~main.iframe.bundle.js:215952:18)
    at updateForwardRef (http://localhost:6006/vendors~main.iframe.bundle.js:218011:20)
    at beginWork (http://localhost:6006/vendors~main.iframe.bundle.js:220065:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.iframe.bundle.js:204912:14)
```

# 考えられる原因
調査中

**Comment by r-kunisawa** [comment]
調査したところ以下のことが分かりました。

## 原因のファイル

```
components/organisms/SearchArea/styled.tsx
```

## 推測される原因
mui/material/stylesのstyledがimportされておらず, styled-componentsのstyledのみがimportされており, themeの参照が正常にされていなかったため。

## 解決方法
@mui/material/stylesのstyledをエイリアス名を使用してインポートし, themeを使っている箇所のstyledの記述をエイリアス名のものに変更する。

例えば, 9行目に下記を追加し,

```
import { styled as styles } from "@mui/material/styles";
```

その後, 11,23,28行目にあるexport文のstyledをstylesに変更する。

**Comment by fukudomeh** [comment]
@r-kunisawa 
ありがとうございます！
よければ、こちらのissueお任せしてもよろしいでしょうか！😊

**Comment by r-kunisawa** [comment]
@fukudomeh 

> よければ、こちらのissueお任せしてもよろしいでしょうか！😊

承知いたしました。
